

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true



mybatis:
  #mapper 映射文件配置
  mapper-locations: classpath:mapper/*.xml
  #添加包扫描
  type-aliases-package: com.example.springbootdemo.pojo
  #mybatis核心配置文件
  # check-config-location:
server:
  port: 9090